export const MAX_PROPOSAL_DESCRIPTION_LENGTH = 1200;
export const MAX_PROPOSAL_PHOTOS = 5;
export const MAX_PROPOSAL_DURATION_HOURS = 24;
export const MAX_PROPOSAL_DURATION_DAYS = 7;
export const PROPOSAL_PRICING_DEBOUNCE_MS = 1500;
