export type ProposalCopyVariant = "proposal" | "budget";

export const PROPOSAL_COPY_VARIANTS = {
  proposal: {
    detailsTitle: "Detalhes da proposta",
    amountLabel: "Valor",
    updatedAtLabel: "Última atualização",
    loadingDetails: "Carregando detalhes da proposta…",
    loadingHistory: "Não foi possível carregar o histórico de propostas.",
    emptyHistory: "Nenhuma proposta encontrada.",
    historyTrigger: "Ver histórico de propostas",
    historyDetailsAria: "Ver detalhes da proposta",
    photosHeading: "Fotos da proposta",
    photoAltPrefix: "Foto da proposta",
    summaryLatestTitle: "Sua proposta mais recente enviada",
    summaryDetailsTitle: "Detalhes da proposta",
    editAction: "Editar proposta",
    amountInformedLabel: "Valor informado",
    statusLabel: "Status da proposta",
    descriptionLabel: "Descrição da proposta",
  },
  budget: {
    detailsTitle: "Detalhes do orçamento",
    amountLabel: "Valor cobrado",
    updatedAtLabel: "Última edição",
    loadingDetails: "Carregando detalhes do orçamento…",
    loadingHistory: "Não foi possível carregar o histórico de orçamentos.",
    emptyHistory: "Nenhum orçamento encontrado para este trabalho.",
    historyTrigger: "Ver histórico de orçamentos",
    historyDetailsAria: "Ver detalhes do orçamento",
    photosHeading: "Fotos do orçamento",
    photoAltPrefix: "Foto do orçamento",
    summaryLatestTitle: "Seu orçamento mais recente enviado",
    summaryDetailsTitle: "Detalhes do orçamento",
    editAction: "Editar orçamento",
    amountInformedLabel: "Valor informado",
    statusLabel: "Status do orçamento",
    descriptionLabel: "Descrição do orçamento",
  },
} as const satisfies Record<ProposalCopyVariant, Record<string, string>>;
