import type {
  SuggestedEquipmentKey,
  SuggestedMaterialsKey,
} from "@/lib/contracts/generate-smart-description/allowedValues";

export const EQUIPMENT_LABEL_MAP: Record<SuggestedEquipmentKey, string> = {
  insulated_screwdrivers: "Chaves de fenda isoladas",
  wire_strippers: "Alicate desencapador de fios",
  voltage_tester: "Testador de tensão",
  multimeter: "Multímetro",
  cable_cutter: "Cortador de cabos",
  conduit_bender: "Curvador de eletroduto",
  ladder: "Escada",
  step_ladder: "Escada de abrir",
  extension_ladder: "Escada extensível",
  pipe_wrench: "Chave grifo",
  plunger: "Desentupidor",
  drain_snake: "Mola desentupidora",
  pipe_cutter: "Cortador de tubos",
  propane_torch: "Maçarico a propano",
  level: "Nível",
  laser_level: "Nível a laser",
  measuring_tape: "Trena",
  drill: "Furadeira",
  impact_drill: "Furadeira de impacto",
  hammer_drill: "Martelete",
  screwdriver_set: "Jogo de chaves de fenda",
  safety_goggles: "Óculos de proteção",
  work_gloves: "Luvas de trabalho",
  knee_pads: "Joelheiras",
  dust_mask: "Máscara contra poeira",
  hearing_protection: "Protetor auricular",
  trowel: "Colher de pedreiro",
  float: "Desempenadeira",
  mixing_drill: "Misturador elétrico",
  vacuum_pump: "Bomba de vácuo",
  manifold_gauges: "Manifold de refrigeração",
  leak_detector: "Detector de vazamento",
  circular_saw: "Serra circular",
  jigsaw: "Serra tico-tico",
  router: "Tupia",
  clamps: "Grampos",
  angle_grinder: "Esmerilhadeira angular",
  reciprocating_saw: "Serra sabre",
  nail_gun: "Pistola de pregos",
  staple_gun: "Grampeador",
  caulking_gun: "Pistola aplicadora de selante",
  paint_roller: "Rolo de pintura",
  paint_brush: "Pincel",
  paint_tray: "Bandeja de pintura",
  sandpaper: "Lixa",
  masking_tape: "Fita crepe",
  scaffolding: "Andaime",
  safety_harness: "Cinto de segurança",
  wheelbarrow: "Carrinho de mão",
  shovel: "Pá",
  pickaxe: "Picareta",
  sledgehammer: "Marreta",
  chisel: "Formão",
  mallet: "Macete",
  wrench_set: "Jogo de chaves",
  socket_set: "Jogo de soquetes",
  pliers: "Alicate",
  needle_nose_pliers: "Alicate de bico",
  crescent_wrench: "Chave inglesa",
  tubing_cutter: "Cortador de tubos",
  flaring_tool: "Flangeador",
  thread_seal_tape: "Fita veda rosca",
  stud_finder: "Detector de vigas",
  thermal_imager: "Câmera termográfica",
  moisture_meter: "Medidor de umidade",
  pressure_gauge: "Manômetro",
  inspection_camera: "Câmera de inspeção",
  wire_fish_tape: "Passa-fio",
  crimping_tool: "Alicate de crimpagem",
  terminal_driver: "Chave para borne",
  hole_saw_kit: "Jogo de serra copo",
  drywall_saw: "Serra para drywall",
  putty_knife: "Espátula",
  tap_set: "Jogo de machos",
  reamer: "Escareador",
  deburring_tool: "Rebarbador",
  pipe_threader: "Rosqueadeira de tubos",
  basin_wrench: "Chave para lavatório",
  faucet_key: "Chave para torneira",
  toilet_plunger: "Desentupidor para vaso sanitário",
  auger: "Trado",
  wet_dry_vacuum: "Aspirador de pó e água",
  air_compressor: "Compressor de ar",
  nail_set: "Puncionador de pregos",
  wood_chisel: "Formão para madeira",
  plane: "Plaina manual",
  miter_saw: "Serra de meia-esquadria",
  table_saw: "Serra de bancada",
  belt_sander: "Lixadeira de cinta",
  orbital_sander: "Lixadeira orbital",
  paint_sprayer: "Pistola de pintura",
  pressure_washer: "Lavadora de alta pressão",
  concrete_mixer: "Betoneira",
  vibrator_concrete: "Vibrador de concreto",
  rebar_cutter: "Cortador de vergalhão",
  brick_trowel: "Colher para assentamento de tijolos",
  pointing_trowel: "Colher de rejunte",
  margin_trowel: "Colher de canto",
  edger: "Acabadora de borda",
  groover: "Frisador de juntas",
  tile_cutter: "Cortador de piso",
  wet_saw: "Serra úmida",
  notched_trowel: "Desempenadeira dentada",
  rubber_mallet: "Martelo de borracha",
  spacers: "Espaçadores",
  grout_float: "Desempenadeira para rejunte",
  sponge: "Esponja",
  hammer: "Martelo",
  utility_knife: "Estilete",
  pry_bar: "Pé de cabra",
  crowbar: "Alavanca",
  work_light: "Luminária de trabalho",
  extension_cord: "Extensão elétrica",
  chalk_line: "Linha de giz",
  hand_saw: "Serrote",
  coping_saw: "Serra de arco",
  miter_box: "Caixa de meia-esquadria",
  drop_cloth: "Lona de proteção",
  extension_pole: "Prolongador para pintura",
  paint_stirrer: "Misturador de tinta",
  sanding_block: "Taco de lixa",
  bull_float: "Desempenadeira de cabo longo",
  concrete_screed: "Régua para concreto",
  tamper: "Soquete manual",
  power_trowel: "Alisadora de concreto",
  roofing_shovel: "Pá para telhado",
  roofing_hammer: "Martelo de telhador",
  wire_puller: "Puxador de cabos",
  knockout_punch: "Saca-bocado para eletroduto",
  drain_cleaning_machine: "Máquina desentupidora",
  pipe_locator: "Localizador de tubulações",
  recovery_machine: "Máquina recolhedora de fluido refrigerante",
  refrigerant_scale: "Balança para fluido refrigerante",
  carpet_cleaner: "Lavadora de carpetes",
  steam_cleaner: "Limpadora a vapor",
  floor_polisher: "Polidora de piso",
  flooring_nailer: "Pregador para piso",
  pull_bar: "Barra de tração",
  tapping_block: "Bloco de batida",
  glass_cutter: "Cortador de vidro",
  glazing_tool: "Ferramenta para vidraceiro",
  lawn_mower: "Cortador de grama",
  trimmer: "Aparador de grama",
  hedge_trimmer: "Aparador de cerca-viva",
  chainsaw: "Motosserra",
  leaf_blower: "Soprador de folhas",
  rake: "Rastelo",
  hoe: "Enxada",
  appliance_dolly: "Carrinho para eletrodomésticos",
  bench_grinder: "Esmeril de bancada",
  file_rasp: "Lima grosa",
  sharpening_stone: "Pedra de afiar",
  metal_shears: "Tesoura para chapa",
  hacksaw: "Arco de serra",
  pipe_freezer: "Congelador de tubos",
  sewer_rod: "Haste para desobstrução de esgoto",
  bucket: "Balde",
  mixing_bucket: "Balde de mistura",
  safety_cones: "Cones de segurança",
  warning_tape: "Fita de sinalização",
  carpet_knee_kicker: "Esticador de carpete de joelho",
  seam_roller: "Rolo para emendas",
  toolbox: "Caixa de ferramentas",
  tool_belt: "Cinto porta-ferramentas",
  magnetic_wristband: "Pulseira magnética",
  step_stool: "Banqueta de apoio",
  workbench: "Bancada de trabalho",
  sawhorses: "Cavaletes",
  bench_vise: "Morsa de bancada",
  speed_square: "Esquadro rápido",
  framing_square: "Esquadro de carpinteiro",
  combination_square: "Esquadro combinado",
  digital_level: "Nível digital",
  angle_finder: "Medidor de ângulo",
  measuring_wheel: "Roda de medição",
  marking_gauge: "Graminho",
  carpenter_pencil: "Lápis de carpinteiro",
  marker: "Marcador",
  non_contact_voltage_tester: "Testador de tensão sem contato",
  cable_tester: "Testador de cabos",
  network_cable_tester: "Testador de cabo de rede",
  insulation_tester: "Megômetro",
  label_maker: "Rotulador",
  wire_marker: "Marcador de fios",
  fish_rods: "Varetas passa-fio",
  cable_crimper: "Alicate crimpa-cabos",
  cable_stripper: "Decapador de cabos",
  strap_wrench: "Chave de cinta",
  internal_pipe_wrench: "Chave interna para tubos",
  pipe_bending_spring: "Mola curvadora de tubos",
  pipe_expander: "Expansor de tubos",
  press_tool_pex: "Prensa para PEX",
  drain_camera: "Câmera para tubulação",
  pipe_inspection_camera: "Câmera de inspeção de tubulação",
  pipe_press_tool: "Prensa para tubos",
  masonry_hammer: "Martelo de pedreiro",
  brick_hammer: "Martelo para tijolo",
  masonry_chisel: "Talhadeira",
  rebar_tying_tool: "Amarrador de vergalhão",
  rebar_bender: "Dobrador de vergalhão",
  mortar_mixer: "Misturador de argamassa",
  hand_tamper: "Soquete manual",
  concrete_edger: "Acabadora de borda para concreto",
  concrete_broom: "Vassoura para acabamento de concreto",
  drywall_lift: "Elevador de chapas drywall",
  drywall_t_square: "Esquadro T para drywall",
  drywall_sander: "Lixadeira para drywall",
  corner_trowel: "Desempenadeira de canto",
  mud_pan: "Bandeja para massa",
  taping_knife: "Espátula para drywall",
  paint_bucket: "Balde para pintura",
  paint_grid: "Grade para pintura",
  paint_scraper: "Raspador de tinta",
  wall_scraper: "Raspador de parede",
  paint_edger: "Aparador para pintura",
  spray_mask: "Máscara para pintura em spray",
  pocket_hole_jig: "Gabarito para furo de bolso",
  dovetail_jig: "Gabarito para junta rabo de andorinha",
  wood_router_bits: "Fresas para tupia",
  drill_press: "Furadeira de bancada",
  planer: "Plaina elétrica",
  thickness_planer: "Plaina desengrossadeira",
  band_saw: "Serra de fita",
  wood_lathe: "Torno para madeira",
  tile_leveling_system: "Sistema nivelador de piso",
  tile_nippers: "Torquês para azulejo",
  tile_spacer_tool: "Ferramenta para espaçadores de piso",
  grout_removal_tool: "Removedor de rejunte",
  tile_vibrator: "Vibrador para assentamento de piso",
  hard_hat: "Capacete de segurança",
  face_shield: "Protetor facial",
  respirator: "Respirador",
  high_visibility_vest: "Colete refletivo",
  steel_toe_boots: "Botas com biqueira de aço",
  first_aid_kit: "Kit de primeiros socorros",
  fire_extinguisher: "Extintor de incêndio",
  generator: "Gerador",
  portable_power_station: "Estação de energia portátil",
  battery_charger: "Carregador de bateria",
  power_inverter: "Inversor de energia",
  extension_reel: "Carretel de extensão",
  measuring_laser: "Medidor a laser",
  laser_distance_meter: "Medidor de distância a laser",
  tablet: "Tablet",
  smartphone: "Smartphone",
  camera: "Câmera",
  portable_printer: "Impressora portátil",
  jobsite_radio: "Rádio para obra",
  other: "Outro",
} as const;

export const MATERIALS_LABEL_MAP: Record<SuggestedMaterialsKey, string> = {
  wire_nuts: "Conectores de torção",
  electrical_tape: "Fita isolante",
  conduit: "Eletroduto",
  junction_boxes: "Caixas de passagem",
  breakers: "Disjuntores",
  cable_wire: "Cabos elétricos",
  outlets: "Tomadas",
  switches: "Interruptores",
  pipes_pvc: "Tubos de PVC",
  pipes_copper: "Tubos de cobre",
  pipes_pex: "Tubos PEX",
  fittings: "Conexões",
  sealant: "Selante",
  plumbers_tape: "Fita veda rosca",
  pipe_cement: "Adesivo para tubos",
  drain_cleaner: "Desentupidor químico",
  paint: "Tinta",
  primer: "Primer",
  thinner: "Thinner",
  screws: "Parafusos",
  nails: "Pregos",
  anchors: "Buchas",
  adhesives: "Adesivos",
  caulk: "Calafetador",
  expanding_foam: "Espuma expansiva",
  insulation: "Isolamento",
  drywall: "Drywall",
  joint_compound: "Massa para juntas",
  mesh_tape: "Fita telada",
  sandpaper: "Lixa",
  wood_filler: "Massa para madeira",
  putty: "Massa corrida",
  grout: "Rejunte",
  tile_adhesive: "Argamassa colante",
  tiles: "Pisos e revestimentos",
  cement: "Cimento",
  mortar: "Argamassa",
  sand: "Areia",
  gravel: "Brita",
  rebar: "Vergalhão",
  wire_mesh: "Tela de aço",
  roofing_nails: "Pregos para telhado",
  shingles: "Shingles",
  flashing: "Rufo",
  roofing_cement: "Cimento asfáltico",
  gutters: "Calhas",
  downspouts: "Condutores de água pluvial",
  screws_metal: "Parafusos para metal",
  bolts: "Parafusos com porca",
  washers: "Arruelas",
  nuts: "Porcas",
  lubricant: "Lubrificante",
  filter: "Filtro",
  refrigerant: "Fluido refrigerante",
  thermostat: "Termostato",
  duct_tape: "Fita silver tape",
  ductwork: "Dutos",
  vent_covers: "Grelhas de ventilação",
  gasket: "Junta de vedação",
  o_ring: "Anel O-ring",
  cartridge: "Cartucho",
  washer_replacement: "Arruela de reposição",
  valve: "Válvula",
  hose: "Mangueira",
  clamp: "Abraçadeira",
  strainer: "Ralo",
  trap: "Sifão",
  flange: "Flange",
  wax_ring: "Anel de vedação com cera",
  toilet_repair_kit: "Kit de reparo para vaso sanitário",
  faucet_cartridge: "Cartucho para torneira",
  aerator: "Arejador",
  water_heater_element: "Resistência para aquecedor de água",
  fuse: "Fusível",
  connectors: "Conectores",
  conduit_fittings: "Conexões para eletroduto",
  gfci_outlet: "Tomada com proteção DR",
  led_bulbs: "Lâmpadas LED",
  lamp_holder: "Soquete para lâmpada",
  switch_plate: "Espelho de interruptor",
  faceplate: "Placa de acabamento",
  cable_clips: "Clipes para cabos",
  cable_staples: "Grampos para cabos",
  panel_board: "Quadro de distribuição",
  pvc_primer: "Primer para PVC",
  abs_cement: "Adesivo para ABS",
  flex_connector: "Conector flexível",
  water_heater_anode: "Ânodo para aquecedor de água",
  roller_cover: "Refil de rolo de pintura",
  painter_tape: "Fita para pintura",
  drywall_screws: "Parafusos para drywall",
  corner_bead: "Cantoneira para drywall",
  underlayment: "Manta de base",
  flooring_adhesive: "Adesivo para piso",
  transition_strip: "Perfil de transição",
  quarter_round: "Rodapé meia-cana",
  baseboard: "Rodapé",
  roofing_felt: "Manta asfáltica para telhado",
  ridge_vent: "Ventilação de cumeeira",
  soffit_vent: "Ventilação de beiral",
  duct_sealer: "Selante para dutos",
  register: "Difusor de ar",
  concrete_sealer: "Selador para concreto",
  water_proofing_membrane: "Membrana impermeabilizante",
  expansion_joint: "Junta de dilatação",
  mulch: "Cobertura vegetal",
  soil: "Terra",
  fertilizer: "Fertilizante",
  cleaning_solution: "Solução de limpeza",
  degreaser: "Desengordurante",
  silicone_sealant: "Selante de silicone",
  flex_tape: "Fita flexível de vedação",
  roofing_sealant: "Selante para telhado",
  sod: "Grama em placas",
  gravel_mulch: "Pedrisco decorativo",
  stain: "Stain",
  varnish: "Verniz",
  wood_sealer: "Selador para madeira",
  roofing_screws: "Parafusos para telhado",
  heat_shrink_tube: "Tubo termorretrátil",
  wire_labels: "Etiquetas para fios",
  cable_tray: "Eletrocalha",
  ground_wire: "Fio terra",
  busbar: "Barramento",
  electrical_box_extender: "Extensor de caixa elétrica",
  conduit_strap: "Abraçadeira para eletroduto",
  surge_protector: "Protetor contra surtos",
  pipe_insulation: "Isolamento para tubos",
  pipe_hangers: "Suportes para tubulação",
  water_supply_line: "Engate flexível",
  shutoff_valve: "Registro de fechamento",
  ball_valve: "Válvula de esfera",
  check_valve: "Válvula de retenção",
  pressure_regulator: "Regulador de pressão",
  drain_pipe: "Tubo de esgoto",
  paint_thickener: "Espessante para tinta",
  paint_conditioner: "Condicionador para tinta",
  spray_paint: "Tinta spray",
  textured_paint: "Tinta texturizada",
  paint_remover: "Removedor de tinta",
  wood_primer: "Primer para madeira",
  metal_primer: "Primer para metal",
  wood_glue: "Cola para madeira",
  epoxy_resin: "Resina epóxi",
  wood_dowels: "Cavilhas de madeira",
  laminate_sheet: "Laminado",
  veneer: "Lâmina de madeira",
  melamine_board: "Placa de melamina",
  mdf_board: "Placa de MDF",
  plywood: "Compensado",
  lime: "Cal",
  plaster: "Gesso",
  gypsum: "Gipsita",
  self_leveling_compound: "Massa autonivelante",
  construction_adhesive: "Adesivo de construção",
  anchor_bolts: "Parabolts",
  chemical_anchor: "Chumbador químico",
  tie_wire: "Arame recozido",
  formwork_oil: "Desmoldante para formas",
  drywall_corner_tape: "Fita para canto de drywall",
  drywall_patch: "Remendo para drywall",
  drywall_adhesive: "Adesivo para drywall",
  soundproof_insulation: "Isolamento acústico",
  floor_leveler: "Nivelador de piso",
  grout_sealer: "Selador para rejunte",
  tile_backer_board: "Placa cimentícia para piso/revestimento",
  anti_fracture_membrane: "Membrana antifissura",
  roof_underlayment: "Subcobertura para telhado",
  roof_seal_tape: "Fita de vedação para telhado",
  roofing_membrane: "Membrana para telhado",
  roof_vent_boot: "Base de vedação para respiro de telhado",
  drip_edge: "Pingadeira",
  air_filter: "Filtro de ar",
  condensate_pump: "Bomba de condensado",
  line_set: "Linha frigorígena",
  insulated_duct: "Duto isolado",
  duct_hanger: "Suporte para duto",
  duct_clamp: "Abraçadeira para duto",
  construction_bags: "Sacos para entulho",
  dust_collector_bags: "Sacos para coletor de pó",
  absorbent_cloth: "Pano absorvente",
  scrubbing_pad: "Fibra de limpeza",
  other: "Outro",
} as const;

export function mapSuggestedEquipmentToPt(
  suggestedEquipment: string[] | null
): string[] {
  if (!suggestedEquipment?.length) return [];
  return suggestedEquipment.flatMap((value) => {
    const label = EQUIPMENT_LABEL_MAP[value as SuggestedEquipmentKey];
    return label ? [label] : [];
  });
}

export function mapSuggestedMaterialsToPt(
  suggestedMaterials: string[] | null
): string[] {
  if (!suggestedMaterials?.length) return [];
  return suggestedMaterials.flatMap((value) => {
    const label = MATERIALS_LABEL_MAP[value as SuggestedMaterialsKey];
    return label ? [label] : [];
  });
}
