-- Growth-phase stub (task 110, design §3.6). NOT applied in MVP migrations.
-- Run manually during a maintenance window after backup and load validation.
-- Preconditions: audit table is heap (see platform_constants audit_partitioning_phase).

-- 1) Create monthly RANGE-partitioned parent (PK includes partition key for Postgres 15+).
create table message_dispatcher.message_dispatcher_audit_partitioned (
  id bigint generated by default as identity,
  dispatch_id uuid not null references message_dispatcher.message_dispatches (id) on delete cascade,
  profile_id uuid not null,
  old_status message_dispatcher.message_dispatch_status,
  new_status message_dispatcher.message_dispatch_status not null,
  changed_by text not null default 'system',
  correlation_id uuid,
  delta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);

-- 2) Example partition (adjust bounds per month at cutover).
create table message_dispatcher.message_dispatcher_audit_y2026m05
  partition of message_dispatcher.message_dispatcher_audit_partitioned
  for values from ('2026-05-01') to ('2026-06-01');

create index message_dispatcher_audit_y2026m05_dispatch_created_idx
  on message_dispatcher.message_dispatcher_audit_y2026m05 (dispatch_id, created_at desc);

create index message_dispatcher_audit_y2026m05_profile_created_idx
  on message_dispatcher.message_dispatcher_audit_y2026m05 (profile_id, created_at desc);

-- 3) Backfill + swap (outline — customize in runbook):
-- insert into message_dispatcher_audit_partitioned select * from message_dispatcher_audit;
-- alter trigger ... set search_path; repoint inserts;
-- alter table rename; recreate default partition for future months via cron job.
