-- Multichannel Message Dispatcher (MMD) — migration 3 of 4 (design §13.1).
-- Audit trigger on message_dispatches (tasks 38–39 in docs/message-dispatcher/tasks.md).

-- Append-only audit on status / schedule / lease changes (design §3.6.1, task 38).
create or replace function message_dispatcher.message_dispatcher_audit_on_dispatch_update()
returns trigger
language plpgsql
security definer
set search_path = message_dispatcher, public, auth
as $$
begin
  if tg_op = 'UPDATE'
    and (
      old.status is distinct from new.status
      or old.scheduled_for is distinct from new.scheduled_for
      or old.locked_until is distinct from new.locked_until
    )
  then
    insert into message_dispatcher.message_dispatcher_audit (
      dispatch_id,
      profile_id,
      old_status,
      new_status,
      correlation_id,
      delta,
      changed_by
    )
    values (
      new.id,
      new.profile_id,
      old.status,
      new.status,
      new.correlation_id,
      jsonb_build_object(
        'scheduled_for', jsonb_build_object('old', old.scheduled_for, 'new', new.scheduled_for),
        'locked_until', jsonb_build_object('old', old.locked_until, 'new', new.locked_until),
        'retry_count', jsonb_build_object('old', old.retry_count, 'new', new.retry_count),
        'failure_code', new.failure_code,
        'metadata', new.metadata
      ),
      coalesce(nullif(current_setting('app.changed_by', true), ''), 'system')
    );
  end if;

  return new;
end;
$$;

comment on function message_dispatcher.message_dispatcher_audit_on_dispatch_update() is
  'AFTER UPDATE trigger fn: append audit row on status, scheduled_for, or locked_until change.';

drop trigger if exists trg_message_dispatcher_audit on message_dispatcher.message_dispatches;

create trigger trg_message_dispatcher_audit
  after update on message_dispatcher.message_dispatches
  for each row
  execute function message_dispatcher.message_dispatcher_audit_on_dispatch_update();

-- Task 110: Growth stub — monthly RANGE(created_at) partitioning (design §3.6). MVP stays unpartitioned.
insert into public.platform_constants (key, value)
values ('message_dispatcher.audit_partitioning_phase', to_jsonb('mvp_unpartitioned'::text))
on conflict (key) do update set
  value = excluded.value,
  updated_at = now();

create or replace function message_dispatcher.message_dispatcher_audit_partitioning_growth_stub_sql()
returns text
language sql
immutable
security definer
set search_path = message_dispatcher, public, auth
as $$
  select $stub$
-- Growth cutover stub (task 110). Executable copy: supabase/scripts/growth/message_dispatcher_audit_monthly_partitions.sql
-- PARTITION BY RANGE (created_at) monthly; per-partition indexes for Req. 6 AC3.

create table message_dispatcher.message_dispatcher_audit_partitioned (
  id bigint generated by default as identity,
  dispatch_id uuid not null,
  profile_id uuid not null,
  old_status message_dispatcher.message_dispatch_status,
  new_status message_dispatcher.message_dispatch_status not null,
  changed_by text not null default 'system',
  correlation_id uuid,
  delta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);

-- create table message_dispatcher_audit_yYYYYmMM partition of ... for values from (...) to (...);
-- create index ... on each child (dispatch_id, created_at desc) and (profile_id, created_at desc);
$stub$::text;
$$;

comment on function message_dispatcher.message_dispatcher_audit_partitioning_growth_stub_sql() is
  'Returns Growth-phase DDL outline for monthly audit partitions (not executed in MVP, task 110).';

revoke all on function message_dispatcher.message_dispatcher_audit_partitioning_growth_stub_sql() from public;
revoke all on function message_dispatcher.message_dispatcher_audit_partitioning_growth_stub_sql() from authenticated;
grant execute on function message_dispatcher.message_dispatcher_audit_partitioning_growth_stub_sql() to postgres;
grant execute on function message_dispatcher.message_dispatcher_audit_partitioning_growth_stub_sql() to service_role;
