import { useRef, useEffect } from "react";
import { Loader2, Sparkles, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { RequestQuoteState } from "../../hooks/useRequestQuoteState";
import { useGenerateSmartDescription } from "../../hooks/useGenerateSmartDescription";

export interface Step3DescriptionPhotosProps {
  state: RequestQuoteState;
}

export function Step3DescriptionPhotos({ state }: Step3DescriptionPhotosProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const hasAutoGenerated = useRef(false);
  const { generateSmartDescription } = useGenerateSmartDescription({ state });

  const { description, photos } = state.step3Data;
  const generatingDescription = state.generatingDescription;

  const onDescriptionChange = (value: string) => {
    state.setStep3Data((prev) => ({ ...prev, description: value }));
  };

  const onPhotosChange = (files: File[], previews: string[]) => {
    state.setStep3Data((prev) => ({ ...prev, photos: files, photoPreviews: previews }));
  };

  // Auto-generate description once when entering step 3 with empty description
  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (!description.trim()) {
      hasAutoGenerated.current = true;
      generateSmartDescription();
    }
  }, [description, generateSmartDescription]);

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-semibold text-white">Descrição e fotos</h2>
      {generatingDescription && (
        <div className="flex items-center gap-2 rounded-lg bg-white/10 px-4 py-3 text-white">
          <Loader2 className="h-5 w-5 shrink-0 animate-spin" />
          <span>Gerando descrição automaticamente...</span>
        </div>
      )}
      <div>
        <Label className="text-white/90">Descrição do serviço</Label>
        <div className="flex gap-2 mt-1">
          <Textarea
            value={description}
            onChange={(e) => onDescriptionChange(e.target.value)}
            placeholder="Descreva o que você precisa..."
            className="min-h-[120px] bg-white/10 border-white/30 text-white placeholder:text-white/50"
          />
          <Button
            type="button"
            size="icon"
            variant="outline"
            className="shrink-0 border-white/30 text-white"
            onClick={() => generateSmartDescription()}
            disabled={generatingDescription}
          >
            {generatingDescription ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="h-4 w-4" />
            )}
          </Button>
        </div>
      </div>
      <div>
        <Label className="text-white/90">Fotos (opcional)</Label>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          multiple
          className="hidden"
          onChange={(e) => {
            const files = Array.from(e.target.files ?? []);
            onPhotosChange(
              files,
              files.map((f) => URL.createObjectURL(f))
            );
          }}
        />
        <Button
          type="button"
          variant="outline"
          className="mt-2 border-white/30 text-white"
          onClick={() => fileInputRef.current?.click()}
        >
          <Upload className="h-4 w-4 mr-2" />
          {photos.length > 0 ? `${photos.length} foto(s)` : "Selecionar fotos"}
        </Button>
      </div>
    </div>
  );
}
