import { useRef, useEffect, useCallback } from "react";
import { Loader2, Sparkles, Upload, Trash2, ImageIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import type { RequestQuoteState } from "../../hooks/useRequestQuoteState";
import { useGenerateSmartDescription } from "../../hooks/useGenerateSmartDescription";

export interface Step3DescriptionPhotosProps {
  state: RequestQuoteState;
}

export function Step3DescriptionPhotos({ state }: Step3DescriptionPhotosProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const hasAutoGenerated = useRef(false);
  const { generateSmartDescription } = useGenerateSmartDescription({ state });

  const { description, photoPreviews } = state.step3Data;
  const generatingDescription = state.generatingDescription;

  const onDescriptionChange = (value: string) => {
    state.setStep3Data((prev) => ({ ...prev, description: value }));
  };

  const processFiles = useCallback(
    (newFiles: File[]) => {
      if (!newFiles.length) return;
      const allPhotos = [...state.step3Data.photos, ...newFiles];
      const newPreviews = newFiles.map((f) => URL.createObjectURL(f));
      const allPreviews = [...state.step3Data.photoPreviews, ...newPreviews];
      state.setStep3Data((prev) => ({ ...prev, photos: allPhotos, photoPreviews: allPreviews }));
    },
    [state]
  );

  const handleFileInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    processFiles(files);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    processFiles(Array.from(e.dataTransfer.files ?? []));
  };

  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleRemovePhoto = (index: number) => {
    state.setStep3Data((prev) => ({
      ...prev,
      photos: prev.photos.filter((_, i) => i !== index),
      photoPreviews: prev.photoPreviews.filter((_, i) => i !== index),
    }));
  };

  useEffect(() => {
    if (hasAutoGenerated.current) return;
    if (!description.trim()) {
      hasAutoGenerated.current = true;
      generateSmartDescription();
    }
  }, [description, generateSmartDescription]);

  return (
    <div className="space-y-4 sm:space-y-6">
      <h1 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-bold text-primary mb-4 sm:mb-6">
        Descrição e Fotos
      </h1>

      {generatingDescription ? (
        <div className="flex flex-col items-center justify-center py-12">
          <Loader2 className="h-12 w-12 text-accent animate-spin mb-4" />
          <p className="text-muted-foreground">✨ Gerando descrição profissional...</p>
        </div>
      ) : (
        <>
          <div>
            <div className="flex items-center justify-between mb-2">
              <Label className="text-base">
                Descrição do Serviço
                <span className="text-muted-foreground text-sm ml-2">
                  (Gerada automaticamente, edite se necessário)
                </span>
              </Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() => {
                  toast.info("Você pode escrever manualmente.");
                  state.setGeneratingDescription(false);
                }}
                className="text-xs"
              >
                <Sparkles className="h-3 w-3 mr-1" />
                Pular IA e escrever
              </Button>
            </div>
            <Textarea
              value={description}
              onChange={(e) => onDescriptionChange(e.target.value)}
              className="min-h-[120px] text-base"
              placeholder="A descrição será gerada automaticamente, ou você pode escrever manualmente..."
            />
          </div>

          <div>
            <Label className="text-base mb-2 block">Fotos (Opcional)</Label>
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept="image/*"
              onChange={handleFileInputChange}
              className="hidden"
            />
            <div
              onClick={() => fileInputRef.current?.click()}
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              className="border-2 border-dashed border-border rounded-xl p-8 text-center hover:border-accent/50 transition-colors cursor-pointer flex flex-col items-center justify-center gap-3"
            >
              <Upload className="h-12 w-12 text-muted-foreground" />
              <p className="text-muted-foreground">Clique ou arraste e solte fotos aqui</p>
              <p className="text-xs text-muted-foreground mt-1">
                PNG, JPG até 10MB cada (otimizamos automaticamente)
              </p>
            </div>

            {photoPreviews.length > 0 && (
              <div className="grid grid-cols-2 md:grid-cols-3 gap-3 mt-4">
                {photoPreviews.map((preview, index) => (
                  <div key={index} className="relative group">
                    <img
                      src={preview}
                      alt={`Preview ${index + 1}`}
                      className="w-full h-32 object-cover rounded-lg border border-border"
                    />
                    <button
                      type="button"
                      onClick={() => handleRemovePhoto(index)}
                      className="absolute top-2 right-2 bg-red-500 text-white p-1.5 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                    >
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                ))}
              </div>
            )}

            {photoPreviews.length === 0 && (
              <div className="flex items-center gap-2 mt-3 text-xs text-muted-foreground">
                <ImageIcon className="w-4 h-4" />
                <span>Adicionar fotos ajuda os profissionais a enviarem orçamentos mais precisos.</span>
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}
